title: <p align="center"> Akankshya Abhilipsa </p>
logo: /assets/img/mypic.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/akankshyaabhilipsa/">LinkedIn</a> |
  <a href="https://github.com/sajankedia">GitHub</a>
  
  <br>   
  Hello, I'm working as a Business Analyst at ABB.
  <br>
  </p>



theme: jekyll-theme-minimal
